defaults:
  - token_classification

preprocessing:
  method:
    map:
      batched: True
      num_proc: 1
      function:
        column_names:
          text: tokens
          label: pos_tags
        label2id:
          ADJ: 0
          ADP: 1
          ADV: 2
          AUX: 3
          CCONJ: 4
          DET: 5
          INTJ: 6
          NOUN: 7
          NUM: 8
          PART: 9
          PRON: 10
          PROPN: 11
          PUNCT: 12
          SCONJ: 13
          SYM: 14
          VERB: 15
          X: 16
