defaults:
  - token_classification

preprocessing:
  method:
    map:
      batched: True
      num_proc: 1
      function:
        column_names:
          text: tokens
          label: ner_tags
        label2id:
          O: 0
          B-PER: 1
          I-PER: 2
          B-ORG: 3
          I-ORG: 4
          B-LOC: 5
          I-LOC: 6
