defaults:
  - default

model:
  _target_: transformers.AutoModel.from_pretrained
  pretrained_model_name_or_path: openai-community/gpt2
  # _convert_: all
  # _target_: torch.nn.Linear
  # _args_:
  #   - 30
  #   - 30

optimizer:
  _target_: bitsandbytes.optim.AdamW8bit
