defaults:
  - xnli_val_test_base
  - /dataspec/nli_gpt2@xnli/validation/en
  - /dataspec/nli_gpt2@xnli/validation/es
  - /dataspec/nli_gpt2@xnli/validation/de
  - /dataspec/nli_gpt2@xnli/validation/fr
  - /dataspec/nli_gpt2@xnli/validation/el
  - /dataspec/nli_gpt2@xnli/validation/bg
  - /dataspec/nli_gpt2@xnli/validation/ru
  - /dataspec/nli_gpt2@xnli/validation/tr
  - /dataspec/nli_gpt2@xnli/validation/ar
  - /dataspec/nli_gpt2@xnli/validation/vi
  - /dataspec/nli_gpt2@xnli/validation/th
  - /dataspec/nli_gpt2@xnli/validation/zh
  - /dataspec/nli_gpt2@xnli/validation/hi
  - /dataspec/nli_gpt2@xnli/validation/sw
  - /dataspec/nli_gpt2@xnli/validation/ur
  - /dataspec/nli_gpt2@xnli/test/en
  - /dataspec/nli_gpt2@xnli/test/es
  - /dataspec/nli_gpt2@xnli/test/de
  - /dataspec/nli_gpt2@xnli/test/fr
  - /dataspec/nli_gpt2@xnli/test/el
  - /dataspec/nli_gpt2@xnli/test/bg
  - /dataspec/nli_gpt2@xnli/test/ru
  - /dataspec/nli_gpt2@xnli/test/tr
  - /dataspec/nli_gpt2@xnli/test/ar
  - /dataspec/nli_gpt2@xnli/test/vi
  - /dataspec/nli_gpt2@xnli/test/th
  - /dataspec/nli_gpt2@xnli/test/zh
  - /dataspec/nli_gpt2@xnli/test/hi
  - /dataspec/nli_gpt2@xnli/test/sw
  - /dataspec/nli_gpt2@xnli/test/ur
