defaults:
  - /dataspec/belebele_llm2vec@eng_Latn/validation
  - /dataspec/belebele_llm2vec@eng_Latn/test

eng_Latn/validation:
  dataset:
    _convert_: all
    path: parquet
    data_files: ${hydra:runtime.cwd}/data/datasets/belebele_train_validation/eng_Latn_val.parquet
    split: train
  preprocessing:
    method:
      map:
        fn_kwargs:
          columns:
            context: passage
            question: question
            label: correct_answer_num
            choices: 
              - answer1
              - answer2
              - answer3
              - answer4
