defaults:
  - /dataspec/belebele_llm2vec@eng_Latn/validation
  - /dataspec/belebele_llm2vec@acm_Arab/test
  - /dataspec/belebele_llm2vec@afr_Latn/test
  - /dataspec/belebele_llm2vec@als_Latn/test
  - /dataspec/belebele_llm2vec@amh_Ethi/test
  - /dataspec/belebele_llm2vec@apc_Arab/test
  - /dataspec/belebele_llm2vec@arb_Arab/test
  - /dataspec/belebele_llm2vec@arb_Latn/test
  - /dataspec/belebele_llm2vec@ars_Arab/test
  - /dataspec/belebele_llm2vec@ary_Arab/test
  - /dataspec/belebele_llm2vec@arz_Arab/test
  - /dataspec/belebele_llm2vec@asm_Beng/test
  - /dataspec/belebele_llm2vec@azj_Latn/test
  - /dataspec/belebele_llm2vec@bam_Latn/test
  - /dataspec/belebele_llm2vec@ben_Beng/test
  - /dataspec/belebele_llm2vec@ben_Latn/test
  - /dataspec/belebele_llm2vec@bod_Tibt/test
  - /dataspec/belebele_llm2vec@bul_Cyrl/test
  - /dataspec/belebele_llm2vec@cat_Latn/test
  - /dataspec/belebele_llm2vec@ceb_Latn/test
  - /dataspec/belebele_llm2vec@ces_Latn/test
  - /dataspec/belebele_llm2vec@ckb_Arab/test
  - /dataspec/belebele_llm2vec@dan_Latn/test
  - /dataspec/belebele_llm2vec@deu_Latn/test
  - /dataspec/belebele_llm2vec@ell_Grek/test
  - /dataspec/belebele_llm2vec@eng_Latn/test
  - /dataspec/belebele_llm2vec@est_Latn/test
  - /dataspec/belebele_llm2vec@eus_Latn/test
  - /dataspec/belebele_llm2vec@fin_Latn/test
  - /dataspec/belebele_llm2vec@fra_Latn/test
  - /dataspec/belebele_llm2vec@fuv_Latn/test
  - /dataspec/belebele_llm2vec@gaz_Latn/test
  - /dataspec/belebele_llm2vec@grn_Latn/test
  - /dataspec/belebele_llm2vec@guj_Gujr/test
  - /dataspec/belebele_llm2vec@hat_Latn/test
  - /dataspec/belebele_llm2vec@hau_Latn/test
  - /dataspec/belebele_llm2vec@heb_Hebr/test
  - /dataspec/belebele_llm2vec@hin_Deva/test
  - /dataspec/belebele_llm2vec@hin_Latn/test
  - /dataspec/belebele_llm2vec@hrv_Latn/test
  - /dataspec/belebele_llm2vec@hun_Latn/test
  - /dataspec/belebele_llm2vec@hye_Armn/test
  - /dataspec/belebele_llm2vec@ibo_Latn/test
  - /dataspec/belebele_llm2vec@ilo_Latn/test
  - /dataspec/belebele_llm2vec@ind_Latn/test
  - /dataspec/belebele_llm2vec@isl_Latn/test
  - /dataspec/belebele_llm2vec@ita_Latn/test
  - /dataspec/belebele_llm2vec@jav_Latn/test
  - /dataspec/belebele_llm2vec@jpn_Jpan/test
  - /dataspec/belebele_llm2vec@kac_Latn/test
  - /dataspec/belebele_llm2vec@kan_Knda/test
  - /dataspec/belebele_llm2vec@kat_Geor/test
  - /dataspec/belebele_llm2vec@kaz_Cyrl/test
  - /dataspec/belebele_llm2vec@kea_Latn/test
  - /dataspec/belebele_llm2vec@khk_Cyrl/test
  - /dataspec/belebele_llm2vec@khm_Khmr/test
  - /dataspec/belebele_llm2vec@kin_Latn/test
  - /dataspec/belebele_llm2vec@kir_Cyrl/test
  - /dataspec/belebele_llm2vec@kor_Hang/test
  - /dataspec/belebele_llm2vec@lao_Laoo/test
  - /dataspec/belebele_llm2vec@lin_Latn/test
  - /dataspec/belebele_llm2vec@lit_Latn/test
  - /dataspec/belebele_llm2vec@lug_Latn/test
  - /dataspec/belebele_llm2vec@luo_Latn/test
  - /dataspec/belebele_llm2vec@lvs_Latn/test
  - /dataspec/belebele_llm2vec@mal_Mlym/test
  - /dataspec/belebele_llm2vec@mar_Deva/test
  - /dataspec/belebele_llm2vec@mkd_Cyrl/test
  - /dataspec/belebele_llm2vec@mlt_Latn/test
  - /dataspec/belebele_llm2vec@mri_Latn/test
  - /dataspec/belebele_llm2vec@mya_Mymr/test
  - /dataspec/belebele_llm2vec@nld_Latn/test
  - /dataspec/belebele_llm2vec@nob_Latn/test
  - /dataspec/belebele_llm2vec@npi_Deva/test
  - /dataspec/belebele_llm2vec@npi_Latn/test
  - /dataspec/belebele_llm2vec@nso_Latn/test
  - /dataspec/belebele_llm2vec@nya_Latn/test
  - /dataspec/belebele_llm2vec@ory_Orya/test
  - /dataspec/belebele_llm2vec@pan_Guru/test
  - /dataspec/belebele_llm2vec@pbt_Arab/test
  - /dataspec/belebele_llm2vec@pes_Arab/test
  - /dataspec/belebele_llm2vec@plt_Latn/test
  - /dataspec/belebele_llm2vec@pol_Latn/test
  - /dataspec/belebele_llm2vec@por_Latn/test
  - /dataspec/belebele_llm2vec@ron_Latn/test
  - /dataspec/belebele_llm2vec@rus_Cyrl/test
  - /dataspec/belebele_llm2vec@shn_Mymr/test
  - /dataspec/belebele_llm2vec@sin_Latn/test
  - /dataspec/belebele_llm2vec@sin_Sinh/test
  - /dataspec/belebele_llm2vec@slk_Latn/test
  - /dataspec/belebele_llm2vec@slv_Latn/test
  - /dataspec/belebele_llm2vec@sna_Latn/test
  - /dataspec/belebele_llm2vec@snd_Arab/test
  - /dataspec/belebele_llm2vec@som_Latn/test
  - /dataspec/belebele_llm2vec@sot_Latn/test
  - /dataspec/belebele_llm2vec@spa_Latn/test
  - /dataspec/belebele_llm2vec@srp_Cyrl/test
  - /dataspec/belebele_llm2vec@ssw_Latn/test
  - /dataspec/belebele_llm2vec@sun_Latn/test
  - /dataspec/belebele_llm2vec@swe_Latn/test
  - /dataspec/belebele_llm2vec@swh_Latn/test
  - /dataspec/belebele_llm2vec@tam_Taml/test
  - /dataspec/belebele_llm2vec@tel_Telu/test
  - /dataspec/belebele_llm2vec@tgk_Cyrl/test
  - /dataspec/belebele_llm2vec@tgl_Latn/test
  - /dataspec/belebele_llm2vec@tha_Thai/test
  - /dataspec/belebele_llm2vec@tir_Ethi/test
  - /dataspec/belebele_llm2vec@tsn_Latn/test
  - /dataspec/belebele_llm2vec@tso_Latn/test
  - /dataspec/belebele_llm2vec@tur_Latn/test
  - /dataspec/belebele_llm2vec@ukr_Cyrl/test
  - /dataspec/belebele_llm2vec@urd_Arab/test
  - /dataspec/belebele_llm2vec@urd_Latn/test
  - /dataspec/belebele_llm2vec@uzn_Latn/test
  - /dataspec/belebele_llm2vec@vie_Latn/test
  - /dataspec/belebele_llm2vec@war_Latn/test
  - /dataspec/belebele_llm2vec@wol_Latn/test
  - /dataspec/belebele_llm2vec@xho_Latn/test
  - /dataspec/belebele_llm2vec@yor_Latn/test
  - /dataspec/belebele_llm2vec@zho_Hans/test
  - /dataspec/belebele_llm2vec@zho_Hant/test
  - /dataspec/belebele_llm2vec@zsm_Latn/test
  - /dataspec/belebele_llm2vec@zul_Latn/test
eng_Latn/validation:
  dataset:
    _convert_: all
    path: parquet
    data_files: ${hydra:runtime.cwd}/data/datasets/belebele_train_validation/eng_Latn_val.parquet
    split: train
  preprocessing:
    method:
      map:
        fn_kwargs:
          columns:
            context: passage
            question: question
            label: correct_answer_num
            choices: 
              - answer1
              - answer2
              - answer3
              - answer4
