defaults:
  - /dataspec/belebele_llm2vec@acm_Arab_translate_test_600M/test
  - /dataspec/belebele_llm2vec@afr_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@als_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@amh_Ethi_translate_test_600M/test
  - /dataspec/belebele_llm2vec@apc_Arab_translate_test_600M/test
  - /dataspec/belebele_llm2vec@arb_Arab_translate_test_600M/test
  - /dataspec/belebele_llm2vec@arb_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ars_Arab_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ary_Arab_translate_test_600M/test
  - /dataspec/belebele_llm2vec@arz_Arab_translate_test_600M/test
  - /dataspec/belebele_llm2vec@asm_Beng_translate_test_600M/test
  - /dataspec/belebele_llm2vec@azj_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@bam_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ben_Beng_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ben_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@bod_Tibt_translate_test_600M/test
  - /dataspec/belebele_llm2vec@bul_Cyrl_translate_test_600M/test
  - /dataspec/belebele_llm2vec@cat_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ceb_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ces_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ckb_Arab_translate_test_600M/test
  - /dataspec/belebele_llm2vec@dan_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@deu_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ell_Grek_translate_test_600M/test
  - /dataspec/belebele_llm2vec@eng_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@est_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@eus_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@fin_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@fra_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@fuv_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@gaz_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@grn_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@guj_Gujr_translate_test_600M/test
  - /dataspec/belebele_llm2vec@hat_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@hau_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@heb_Hebr_translate_test_600M/test
  - /dataspec/belebele_llm2vec@hin_Deva_translate_test_600M/test
  - /dataspec/belebele_llm2vec@hin_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@hrv_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@hun_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@hye_Armn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ibo_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ilo_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ind_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@isl_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ita_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@jav_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@jpn_Jpan_translate_test_600M/test
  - /dataspec/belebele_llm2vec@kac_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@kan_Knda_translate_test_600M/test
  - /dataspec/belebele_llm2vec@kat_Geor_translate_test_600M/test
  - /dataspec/belebele_llm2vec@kaz_Cyrl_translate_test_600M/test
  - /dataspec/belebele_llm2vec@kea_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@khk_Cyrl_translate_test_600M/test
  - /dataspec/belebele_llm2vec@khm_Khmr_translate_test_600M/test
  - /dataspec/belebele_llm2vec@kin_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@kir_Cyrl_translate_test_600M/test
  - /dataspec/belebele_llm2vec@kor_Hang_translate_test_600M/test
  - /dataspec/belebele_llm2vec@lao_Laoo_translate_test_600M/test
  - /dataspec/belebele_llm2vec@lin_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@lit_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@lug_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@luo_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@lvs_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@mal_Mlym_translate_test_600M/test
  - /dataspec/belebele_llm2vec@mar_Deva_translate_test_600M/test
  - /dataspec/belebele_llm2vec@mkd_Cyrl_translate_test_600M/test
  - /dataspec/belebele_llm2vec@mlt_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@mri_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@mya_Mymr_translate_test_600M/test
  - /dataspec/belebele_llm2vec@nld_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@nob_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@npi_Deva_translate_test_600M/test
  - /dataspec/belebele_llm2vec@npi_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@nso_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@nya_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ory_Orya_translate_test_600M/test
  - /dataspec/belebele_llm2vec@pan_Guru_translate_test_600M/test
  - /dataspec/belebele_llm2vec@pbt_Arab_translate_test_600M/test
  - /dataspec/belebele_llm2vec@pes_Arab_translate_test_600M/test
  - /dataspec/belebele_llm2vec@plt_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@pol_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@por_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ron_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@rus_Cyrl_translate_test_600M/test
  - /dataspec/belebele_llm2vec@shn_Mymr_translate_test_600M/test
  - /dataspec/belebele_llm2vec@sin_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@sin_Sinh_translate_test_600M/test
  - /dataspec/belebele_llm2vec@slk_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@slv_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@sna_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@snd_Arab_translate_test_600M/test
  - /dataspec/belebele_llm2vec@som_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@sot_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@spa_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@srp_Cyrl_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ssw_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@sun_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@swe_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@swh_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@tam_Taml_translate_test_600M/test
  - /dataspec/belebele_llm2vec@tel_Telu_translate_test_600M/test
  - /dataspec/belebele_llm2vec@tgk_Cyrl_translate_test_600M/test
  - /dataspec/belebele_llm2vec@tgl_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@tha_Thai_translate_test_600M/test
  - /dataspec/belebele_llm2vec@tir_Ethi_translate_test_600M/test
  - /dataspec/belebele_llm2vec@tsn_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@tso_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@tur_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@ukr_Cyrl_translate_test_600M/test
  - /dataspec/belebele_llm2vec@urd_Arab_translate_test_600M/test
  - /dataspec/belebele_llm2vec@urd_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@uzn_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@vie_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@war_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@wol_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@xho_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@yor_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@zho_Hans_translate_test_600M/test
  - /dataspec/belebele_llm2vec@zho_Hant_translate_test_600M/test
  - /dataspec/belebele_llm2vec@zsm_Latn_translate_test_600M/test
  - /dataspec/belebele_llm2vec@zul_Latn_translate_test_600M/test
