defaults:
  - /dataspec/nli_llm2vec@kardesnlu_az_translate_test_600M/validation
  - /dataspec/nli_llm2vec@kardesnlu_kk_translate_test_600M/validation
  - /dataspec/nli_llm2vec@kardesnlu_ky_translate_test_600M/validation
  - /dataspec/nli_llm2vec@kardesnlu_uz_translate_test_600M/validation
  - /dataspec/nli_llm2vec@kardesnlu_az_translate_test_600M/test
  - /dataspec/nli_llm2vec@kardesnlu_kk_translate_test_600M/test
  - /dataspec/nli_llm2vec@kardesnlu_ky_translate_test_600M/test
  - /dataspec/nli_llm2vec@kardesnlu_uz_translate_test_600M/test
