defaults:
  - /dataspec/nusax_llm2vec@nusax_ace_translate_test_600M/validation
  - /dataspec/nusax_llm2vec@nusax_ban_translate_test_600M/validation
  - /dataspec/nusax_llm2vec@nusax_bjn_translate_test_600M/validation
  - /dataspec/nusax_llm2vec@nusax_bug_translate_test_600M/validation
  - /dataspec/nusax_llm2vec@nusax_ind_translate_test_600M/validation
  - /dataspec/nusax_llm2vec@nusax_jav_translate_test_600M/validation
  - /dataspec/nusax_llm2vec@nusax_min_translate_test_600M/validation
  - /dataspec/nusax_llm2vec@nusax_sun_translate_test_600M/validation
  - /dataspec/nusax_llm2vec@nusax_ace_translate_test_600M/test
  - /dataspec/nusax_llm2vec@nusax_ban_translate_test_600M/test
  - /dataspec/nusax_llm2vec@nusax_bjn_translate_test_600M/test
  - /dataspec/nusax_llm2vec@nusax_bug_translate_test_600M/test
  - /dataspec/nusax_llm2vec@nusax_ind_translate_test_600M/test
  - /dataspec/nusax_llm2vec@nusax_jav_translate_test_600M/test
  - /dataspec/nusax_llm2vec@nusax_min_translate_test_600M/test
  - /dataspec/nusax_llm2vec@nusax_sun_translate_test_600M/test
