defaults:
  - /dataspec/nli_llm2vec@xnli_en/validation
  - /dataspec/nli_llm2vec@xnli_es/validation
  - /dataspec/nli_llm2vec@xnli_de/validation
  - /dataspec/nli_llm2vec@xnli_fr/validation
  - /dataspec/nli_llm2vec@xnli_el/validation
  - /dataspec/nli_llm2vec@xnli_bg/validation
  - /dataspec/nli_llm2vec@xnli_ru/validation
  - /dataspec/nli_llm2vec@xnli_tr/validation
  - /dataspec/nli_llm2vec@xnli_ar/validation
  - /dataspec/nli_llm2vec@xnli_vi/validation
  - /dataspec/nli_llm2vec@xnli_th/validation
  - /dataspec/nli_llm2vec@xnli_zh/validation
  - /dataspec/nli_llm2vec@xnli_hi/validation
  - /dataspec/nli_llm2vec@xnli_sw/validation
  - /dataspec/nli_llm2vec@xnli_ur/validation
  - /dataspec/nli_llm2vec@xnli_en/test
  - /dataspec/nli_llm2vec@xnli_es/test
  - /dataspec/nli_llm2vec@xnli_de/test
  - /dataspec/nli_llm2vec@xnli_fr/test
  - /dataspec/nli_llm2vec@xnli_el/test
  - /dataspec/nli_llm2vec@xnli_bg/test
  - /dataspec/nli_llm2vec@xnli_ru/test
  - /dataspec/nli_llm2vec@xnli_tr/test
  - /dataspec/nli_llm2vec@xnli_ar/test
  - /dataspec/nli_llm2vec@xnli_vi/test
  - /dataspec/nli_llm2vec@xnli_th/test
  - /dataspec/nli_llm2vec@xnli_zh/test
  - /dataspec/nli_llm2vec@xnli_hi/test
  - /dataspec/nli_llm2vec@xnli_sw/test
  - /dataspec/nli_llm2vec@xnli_ur/test
