defaults:
  - /dataspec/nli_llm2vec@xnli_es_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_de_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_fr_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_el_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_bg_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_ru_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_tr_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_ar_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_vi_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_th_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_zh_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_hi_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_sw_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_ur_translate_test_3B/validation
  - /dataspec/nli_llm2vec@xnli_es_translate_test_3B/test
  - /dataspec/nli_llm2vec@xnli_de_translate_test_3B/test
  - /dataspec/nli_llm2vec@xnli_fr_translate_test_3B/test
  - /dataspec/nli_llm2vec@xnli_el_translate_test_3B/test
  - /dataspec/nli_llm2vec@xnli_bg_translate_test_3B/test
  - /dataspec/nli_llm2vec@xnli_ru_translate_test_3B/test
  - /dataspec/nli_llm2vec@xnli_tr_translate_test_3B/test
  - /dataspec/nli_llm2vec@xnli_ar_translate_test_3B/test
  - /dataspec/nli_llm2vec@xnli_vi_translate_test_3B/test
  - /dataspec/nli_llm2vec@xnli_th_translate_test_3B/test
  - /dataspec/nli_llm2vec@xnli_zh_translate_test_3B/test
  - /dataspec/nli_llm2vec@xnli_hi_translate_test_3B/test
  - /dataspec/nli_llm2vec@xnli_sw_translate_test_3B/test
  - /dataspec/nli_llm2vec@xnli_ur_translate_test_3B/test
